### ISSUE TITLE
Spanish version

### ISSUE THREAD

**Issue by JuannmaCh** [Developer-Bear/RNG_FrontDeskPage#1]
Hello!

So I made a Spanish version. Hopefully this will help somebody.

Thanks for the script by the way. Very useful

[RNG_FrontDeskPage spanish.zip](https://github.com/Developer-Bear/RNG_FrontDeskPage/files/4151323/RNG_FrontDeskPage.spanish.zip)

**Comment by Developer-Bear** [comment]
Multi Language support added. I added Spanish translation. You didn't translate the server side so I had to use google translator :D please make a PR if you need to tweak the language further
