### ISSUE TITLE
French version

### ISSUE THREAD

**Issue by clementinise** [Developer-Bear/RNG_FrontDeskPage#3]
Hi!

I made the French locales version of your script since I love it and I want to contribute :D 

`Locales['fr'] = {`
`    ['pageFloatingText']   = "Appuyez sur ~g~L~s~ pour demander de l'assistance",`
`    ['notificationText'] = "Assistance demandé à la réception du ^5%s^7",`
`    ['successfulPage'] = "Vous avez demandé de l'assistance !",`
`    ['recentPage'] = "Une demande d'assistance à déjà reçu, veuillez patienter !",`
`  }`

Big love

**Comment by Developer-Bear** [comment]
added french version, thank you!
